"""Initial migration

Revision ID: 4242a934a757
Revises: 
Create Date: 2025-11-20 19:09:29.136559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4242a934a757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed spatial_ref_sys drop as it's a PostGIS system table
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed spatial_ref_sys creation as it's a PostGIS system table
    pass
    # ### end Alembic commands ###
