"""Unify user model

Revision ID: 61ba53809054
Revises: 1058f7192b73
Create Date: 2025-11-13 01:16:10.411579

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '61ba53809054'
down_revision = '1058f7192b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('bus', 'taxi', 'moto', name='vehicle_type'), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', dimension=2), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('route_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_index(
        'idx_vehicles_location',
        'vehicles',
        ['location'],
        unique=False,
        postgresql_using='gist',
        if_not_exists=True
    )

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', dimension=2), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(
        'idx_zones_boundary',
        'zones',
        ['boundary'],
        unique=False,
        postgresql_using='gist',
        if_not_exists=True
    )

    op.create_table('fare_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('bus', 'taxi', 'moto', name='transport_mode'), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('per_km_rate', sa.Float(), nullable=False),
    sa.Column('per_minute_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('minimum_fare', sa.Float(), nullable=False),
    sa.Column('maximum_fare', sa.Float(), nullable=True),
    sa.Column('peak_hour_multiplier', sa.Float(), nullable=True),
    sa.Column('night_multiplier', sa.Float(), nullable=True),
    sa.Column('peak_start_time', sa.String(length=5), nullable=True),
    sa.Column('peak_end_time', sa.String(length=5), nullable=True),
    sa.Column('night_start_time', sa.String(length=5), nullable=True),
    sa.Column('night_end_time', sa.String(length=5), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('zone_multiplier', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.Enum('overcharge', 'safety', 'service', 'other', name='report_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'resolved', 'dismissed', name='report_status'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='report_priority'), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', dimension=2), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.Enum('bus', 'taxi', 'moto', 'combined', name='stop_type'), nullable=False),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('is_shelter', sa.Boolean(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'idx_stops_location',
        'stops',
        ['location'],
        unique=False,
        postgresql_using='gist',
        if_not_exists=True
    )

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('origin_address', sa.String(length=500), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=True),
    sa.Column('origin_zone_id', sa.Integer(), nullable=True),
    sa.Column('destination_zone_id', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('mode', sa.Enum('bus', 'taxi', 'moto', 'combined', name='transport_mode'), nullable=False),
    sa.Column('estimated_fare', sa.Float(), nullable=True),
    sa.Column('actual_fare', sa.Float(), nullable=True),
    sa.Column('fare_breakdown', sa.Text(), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('route_steps', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='trip_status'), nullable=True),
    sa.Column('planned_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['origin_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # Backfill UUIDs for existing users before enforcing constraints
    conn = op.get_bind()
    users_table = sa.Table(
        'users',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('uuid', sa.String(36))
    )

    result = conn.execute(sa.select(users_table.c.id).where(users_table.c.uuid.is_(None)))
    rows = result.fetchall()
    for row in rows:
        conn.execute(
            sa.update(users_table)
            .where(users_table.c.id == row.id)
            .values(uuid=str(uuid.uuid4()))
        )

    op.alter_column('users', 'uuid', existing_type=sa.String(length=36), nullable=False)
    op.create_unique_constraint('uq_users_uuid', 'users', ['uuid'])
    op.create_unique_constraint('uq_users_phone', 'users', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('phone')
        batch_op.drop_column('uuid')

    op.drop_table('trips')
    op.drop_index('idx_stops_location', table_name='stops', postgresql_using='gist')
    op.drop_table('stops')
    op.drop_table('reports')
    op.drop_table('fare_rules')
    op.drop_index('idx_zones_boundary', table_name='zones', postgresql_using='gist')
    op.drop_table('zones')
    op.drop_index('idx_vehicles_location', table_name='vehicles', postgresql_using='gist')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
